
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MileHighGuy.
--- DateTime: 3/29/2023 8:21 PM
---

-- add our modifications to the screens
-- before they are registered with AddIFScreen


--local originalDoFile = ScriptCB_DoFile
--
--ScriptCB_DoFile = function(filename)
--
--    print("debug: DoFile loaded " .. tostring(filename))
--
--    originalDoFile(filename)
--end

-- add our custom strings
ReadDataFile("..\\..\\addon\\ATO\\localize.lvl")

ScriptCB_DoFile("game_testscript")
ScriptCB_DoFile("ifs_freeform_main_autoresolve")
ScriptCB_DoFile("ifs_freeform_battle_autoresolve")
ScriptCB_DoFile("ifs_freeform_battle_card_autoresolve")
ScriptCB_DoFile("ifs_freeform_battle_mode_autoresolve")

print("ATO: auto resolve script installed successfully")

