---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ben.
--- DateTime: 2/5/2024 7:45 PM
---

if ifs_freeform_battle ~= nil then
    print("DEBUG: added new battle screen button")

    ifs_freeform_battle.Input_Accept = function(this, joystick)
        if(gPlatformStr == "PC") then
            print( "this.CurButton = ", this.CurButton )
            if( this.CurButton == "_accept" ) then
                -- purchase the item
            elseif( this.CurButton == "_autoResolve" ) then
                -- auto resolve match
                -- ========= NEW BUTTON =============
                print("DEBUG: clicked auto resolve")
                ifs_freeform_battle.useAutoResolve = 1
            elseif( this.CurButton == "_back" ) then
                -- handle in Input_Back
                this:Input_Back(joystick)
                return
                --			elseif( this.CurButton == "_next" ) then
                --				return
            else
                return
            end
        end

        ifelm_shellscreen_fnPlaySound(this.acceptSound)

        -- go to the battle mode screen
        ScriptCB_PushScreen("ifs_freeform_battle_mode")
    end -- Input_Accept

    local w,h = ScriptCB_GetSafeScreenInfo()
    local screen_w, screen_h, v, widescreen = ScriptCB_GetScreenInfo()
    local action_w = w
    local action_h = h * 0.05

    if(gPlatformStr == "PC") then
        local BackButtonW = 150	-- made wider to fix 9173 - NM 8/25/04
        local BackButtonH = 25

        local left = BackButtonW * 0.5
        local right = w - BackButtonW * 0.5
        local spacing = (right - left) / 3

        ifs_freeform_battle.action = NewIFContainer{
            ScreenRelativeX = 0.0, -- left
            ScreenRelativeY = 1.0, -- bottom
            width = action_w,
            height = action_h,
            x = 0,
            ZPos = 190,

            misc = NewPCIFButton -- NewRoundIFButton
            {
                x = right - spacing,
                btnw = BackButtonW,
                btnh = BackButtonH,
                font = "gamefont_medium",
                string = "ifs.freeform.endturn",
                tag = "_next",
            }, -- end of btn

            accept = NewPCIFButton -- NewRoundIFButton
            {
                x = right,
                btnw = BackButtonW,
                btnh = BackButtonH,
                font = "gamefont_medium",
                string = "common.accept",
                tag = "_accept",

            }, -- end of btn

            --============== NEW BUTTON FOR AUTORESOLVE ======================
            autoResolve = NewPCIFButton -- NewRoundIFButton
            {
                x = right - spacing,
                btnw = BackButtonW,
                btnh = BackButtonH,
                font = "gamefont_medium",
                string = "Auto Resolve", --"common.accept",
                tag = "_autoResolve",

            }, -- end of btn

            back = NewPCIFButton -- NewRoundIFButton
            {
                x = left,
                btnw = BackButtonW,
                btnh = BackButtonH,
                font = "gamefont_medium",
                string = "common.back",
                tag = "_back",

            }, -- end of btn

            help = NewPCIFButton
            {
                x = left + spacing,
                btnw = BackButtonW,
                btnh = BackButtonH,
                font = "gamefont_medium",
                string = "ifs.freeform.help",
                tag = "_help",
            },
        }
    else
        ifs_freeform_battle.action = NewIFContainer{
            ScreenRelativeX = 0.0, -- left
            ScreenRelativeY = 1.0, -- bottom
            width = action_w,
            height = action_h * 2,
            ZPos = 190,

            misc = NewHelptext {
                x = w*widescreen,
                buttonicon = "btnmisc",
                string = "ifs.freeform.endturn",
                bRightJustify = 1,
                y = -34,
            },


            accept = NewHelptext {
                x = w*widescreen,
                buttonicon = "btna",
                string = "common.accept",
                bRightJustify = 1,
                y = -15,
            },

            back = NewHelptext {
                x = 0,
                buttonicon = "btnb",
                string = "common.back",
                bLeftJustify = 1,
                y = -15,
            },

            help = NewHelptext {
                x = 0,
                buttonicon = "btnmisc2",
                string = "ifs.freeform.help",
                bLeftJustify = 1,
                y = -34,
            },
        }
    end
else
    print("DEBUG: DID NOT add new battle screen button")
end