---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MileHighGuy.
--- DateTime: 2/5/2024 8:10 PM
---

ifs_freeform_battle_card.Next = function(this)

    if this.defending then
        -- switch to the attacker
        this.defending = nil
        ifs_freeform_main:SetActiveTeam(3 - ifs_freeform_main.playerTeam)

        ---- NEW CODE =============
        if ifs_freeform_battle.useAutoResolve then

            -- go back to main to get the result of the battle
            ScriptCB_PopScreen("ifs_freeform_main")
            return -- exit this function
        end

        -- restore split screen
        ScriptCB_SetSplitscreen(ifs_freeform_main.wasSplit)

        -- save state
        ifs_freeform_main:SaveState()

        -- save mission setup
        ifs_freeform_main:SaveMissionSetup()

        -- if in soak mode...
        if ifs_freeform_main.soakMode then
            -- enter the selected mission as a demo
            ScriptCB_LaunchDemo(ifs_freeform_main.launchMission)
        else
            -- enter the selected mission
            ScriptCB_EnterMission()
        end
    else
        -- switch to the defender
        this.defending = true
        ifs_freeform_main:SetActiveTeam(3 - ifs_freeform_main.playerTeam)

        -- re-enter as the defender
        ScriptCB_PushScreen("ifs_freeform_battle_card")
    end
end
