---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MileHighGuy.
--- DateTime: 2/5/2024 7:45 PM
---


ifs_freeform_battle.Enter = function(this, bFwd)
    gIFShellScreenTemplate_fnEnter(this, bFwd) -- call default enter function

    ifs_freeform_main:SetZoom(2)
    MoveCameraToEntity(ifs_freeform_main.planetSelected .. "_camera")

    IFObj_fnSetVis(this.title, nil)

    -- remove player group
    IFObj_fnSetVis(this.player, nil)

    -- allow back only if coming from player fleet movement
    this.allowBack = ifs_freeform_main.joystick and ScriptCB_IsScreenInStack("ifs_freeform_fleet")

    -- update button status
    ifs_freeform_SetButtonVis( this, "back", this.allowBack )
    if ifs_freeform_main.joystick then
        ifs_freeform_SetButtonName( this, "accept", "ifs.freeform.attack" )
        ifs_freeform_SetButtonName( this, "back", "ifs.freeform.noattack" )
    else
        ifs_freeform_SetButtonName( this, "accept", "common.next" )
    end
    ifs_freeform_SetButtonVis(this, "help", nil)

    ---- NEW CODE ===============
    -- is it a space fleet battle?
    local isFleetBattle = ifs_freeform_main.planetFleet[ifs_freeform_main.planetNext] == 0
    local showAutoResolveButton = isFleetBattle
    -- Check remaster mod's database if they set "Auto Resolve For Land Battle" to "Yes"
    -- otherwise its only for space battles
    if rema_database.data.ARLandBattle and rema_database.data.ARLandBattle == 2 then
        print("loaded Auto Resolve For Land Battle")
        showAutoResolveButton = true
    end
    ifs_freeform_SetButtonVis(this, "misc", showAutoResolveButton)
    local autoResolveBtnName = "ifs.freeform.autoresolve"
    -- if there is no localization, just use English
    --if tostring(ScriptCB_ununicode(ScriptCB_getlocalizestr(autoResolveBtnName))) == "[NULL]" then
    --    autoResolveBtnName = "Auto Resolve"
    --end
    --- rename misc to "Auto Resolve"
    ifs_freeform_SetButtonName( this, "misc", autoResolveBtnName )
    ---- end new code

    -- play appropriate VO messages and display caption and info text
    --if it's a deep space battle
    if not ifs_freeform_main.planetTeam[ifs_freeform_main.planetSelected] then
        if ifs_freeform_main.joystick then
            ifs_freeform_main:PlayVoice(string.format(ifs_battle_fleet_sound, ifs_freeform_main.playerSide, "us"))
        else
            ifs_freeform_main:PlayVoice(string.format(ifs_battle_fleet_sound, ifs_freeform_main.otherSide, "them"))
        end
        IFObj_fnSetVis(this.info, true)
        IFText_fnSetString(this.info.caption, "ifs.freeform.spacebattle")
        IFObj_fnSetVis(this.info.text, false)
        --if it's a space battle over a planet
    elseif ifs_freeform_main.planetFleet[ifs_freeform_main.planetSelected] == 0 then
        if ifs_freeform_main.joystick then
            ifs_freeform_main:PlayVoice(string.format(ifs_battle_fleet_sound, ifs_freeform_main.playerSide, "us"))
        else
            ifs_freeform_main:PlayVoice(string.format(ifs_battle_fleet_sound, ifs_freeform_main.otherSide, "them"))
        end
        IFObj_fnSetVis(this.info, true)
        IFText_fnSetString(this.info.text, "ifs.freeform.planetdesc." .. ifs_freeform_main.planetSelected)
        IFObj_fnSetVis(this.info.text, true)
        IFText_fnSetUString(this.info.caption,
                ScriptCB_usprintf("ifs.freeform.fleetbattle",
                        ScriptCB_getlocalizestr("planetname." .. ifs_freeform_main.planetSelected)
                )
        )
        --if it's a planet battle
    else
        if ifs_freeform_main.joystick then
            ifs_freeform_main:PlayVoice(string.format(ifs_battle_planet_sound, ifs_freeform_main.playerSide, ifs_freeform_main.planetSelected, "us"))
        else
            ifs_freeform_main:PlayVoice(string.format(ifs_battle_planet_sound, ifs_freeform_main.otherSide, ifs_freeform_main.planetSelected, "them"))
        end
        IFObj_fnSetVis(this.info, 1)
        IFText_fnSetString(this.info.text, "ifs.freeform.planetdesc." .. ifs_freeform_main.planetSelected)
        IFObj_fnSetVis(this.info.text, true)
        IFText_fnSetUString(this.info.caption,
                ScriptCB_usprintf("ifs.freeform.planetbattle",
                        ScriptCB_getlocalizestr("planetname." .. ifs_freeform_main.planetSelected)
                )
        )
    end

    -- if in soak mode...
    if ifs_freeform_main.soakMode then
        -- start a display timer
        this.displayTimer = 5
    end
end

ifs_freeform_battle.Input_Accept = function(this, joystick)
    if(gPlatformStr == "PC") then
        print( "this.CurButton = ", this.CurButton )
        if( this.CurButton == "_accept" ) then
            -- purchase the item
        ---- NEW CODE =============
        elseif( this.CurButton == "_next" ) then
            -- auto resolve match
            this:Input_Misc(joystick)
            return
        elseif( this.CurButton == "_back" ) then
            -- handle in Input_Back
            this:Input_Back(joystick)
            return
        else
            return
        end
    end

    ifelm_shellscreen_fnPlaySound(this.acceptSound)

    -- go to the battle mode screen
    ScriptCB_PushScreen("ifs_freeform_battle_mode")
end -- Input_Accept

-- this is the X button on console, on PC is it space/ right mouse button
-- Input_Misc2 is the Y button on console
-- Input_Accept is A Input_Back is B on console
ifs_freeform_battle.Input_Misc = function(this, joystick)
    -- set auto resolve flag
    ifs_freeform_battle.useAutoResolve = 1
    ifelm_shellscreen_fnPlaySound(this.acceptSound)
    -- go to the battle mode screen
    ScriptCB_PushScreen("ifs_freeform_battle_mode")
end
