---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MileHighGuy.
--- DateTime: 3/29/2023 8:21 PM
---

if AddIFScreen then

    print("DEBUG: AddIFScreen is defined, overriding")

    local crs_originalAddIfScreen = AddIFScreen
    AddIFScreen = function(tableName, ScreenName)
        print("DEBUG: AddIFScreen " .. tostring(ScreenName))
        if (ScreenName == "ifs_freeform_main") then
        ScriptCB_DoFile("ifs_freeform_main_autoresolve")
        crs_originalAddIfScreen(tableName, ScreenName)
        elseif (ScreenName == "ifs_freeform_battle") then
            ScriptCB_DoFile("ifs_freeform_battle_autoresolve")
            crs_originalAddIfScreen(tableName, ScreenName)
        elseif (ScreenName == "ifs_freeform_battle_card") then
            ScriptCB_DoFile("ifs_freeform_battle_card_autoresolve")
            crs_originalAddIfScreen(tableName, ScreenName)
        elseif (ScreenName == "ifs_freeform_battle_mode") then
            ScriptCB_DoFile("ifs_freeform_battle_mode_autoresolve")
            crs_originalAddIfScreen(tableName, ScreenName)
        else
            crs_originalAddIfScreen(tableName, ScreenName)
        end
    end

else
    print("DEBUG: AddIFScreen is not defined yet!")
end




