---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MileHighGuy.
--- DateTime: 3/29/2023 8:21 PM
---

if AddIFScreen then

    print("DEBUG: AddIFScreen is defined, overriding")

    local crs_originalAddIfScreen = AddIFScreen
    AddIFScreen = function(tableName, ScreenName)
        print("DEBUG: AddIFScreen " .. tostring(ScreenName))
        if (ScreenName == "ifs_freeform_main") then
        ScriptCB_DoFile("ifs_freeform_main_autoresolve")
        crs_originalAddIfScreen(tableName, ScreenName)
        elseif (ScreenName == "ifs_freeform_battle") then
            ScriptCB_DoFile("ifs_freeform_battle_autoresolve")
            crs_originalAddIfScreen(tableName, ScreenName)
        elseif (ScreenName == "ifs_freeform_battle_card") then
            ScriptCB_DoFile("ifs_freeform_battle_card_autoresolve")
            crs_originalAddIfScreen(tableName, ScreenName)
        elseif (ScreenName == "ifs_freeform_result") then
            ScriptCB_DoFile("ifs_freeform_result_autoresolve")
            crs_originalAddIfScreen(tableName, ScreenName)
        else
            crs_originalAddIfScreen(tableName, ScreenName)
        end
    end

else
    print("DEBUG: AddIFScreen is not defined yet!")
end

local gOriginalPushScreen = ScriptCB_PushScreen

ScriptCB_PushScreen = function(screen)
    print("DEBUG: ScriptCB_PushScreen " .. tostring(screen))
    if screen then
        gOriginalPushScreen(screen)
    else
        print("DEBUG: ScriptCB_PushScreen: no screen provided. This should not happen?")
        gOriginalPushScreen()
    end
end

local gOriginalSetScreen = ScriptCB_SetIFScreen
ScriptCB_SetIFScreen = function(screen)
    if screen then
        print("DEBUG: ScriptCB_SetIFScreen " .. tostring(screen))
        gOriginalSetScreen(screen)
    else
        print("DEBUG: ScriptCB_SetIFScreen: no screen provided. This should not happen?")
        gOriginalSetScreen()
    end
end



